name: Stale Bot

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'inactive for 30 days, marking as stale'
          stale-pr-message: 'inactive for 30 days, marking as stale'
          close-issue-message: 'still inactive, closing'
          close-pr-message: 'still inactive, closing'
          days-before-stale: 30
          days-before-close: 7
